import { useState } from 'react'
import { api, getToken } from '../api'
import { dateLocale, useLang } from '../i18n'

/* The document an auditor asks for (#86): every change to a zone in a period,
   with requester, approver, justification and date.

   Rendered rather than downloaded, because the browser's print stylesheet
   already turns it into the PDF that gets emailed - no generator, no extra
   dependency, and the same page an auditor was just shown. CSV is beside it for
   whoever wants to sort it. */
export default function EvidenceReport() {
  const { t, lang } = useLang()
  const today = new Date().toISOString().slice(0, 10)
  const yearStart = `${new Date().getFullYear()}-01-01`
  const [form, setForm] = useState({ date_from: yearStart, date_to: today, zone: '', app_id: '' })
  const [data, setData] = useState(null)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)

  const set = (k) => (e) => { setForm({ ...form, [k]: e.target.value }); setData(null) }

  const params = () => Object.fromEntries(
    Object.entries(form).filter(([, v]) => v !== ''))

  const run = async () => {
    setBusy(true); setError('')
    try {
      setData(await api.evidenceReport(params()))
    } catch (e) {
      setError(e.message)
    } finally {
      setBusy(false)
    }
  }

  const csv = () => {
    fetch(api.evidenceCsvUrl(params()), { headers: { Authorization: `Bearer ${getToken()}` } })
      .then((res) => res.blob())
      .then((blob) => {
        const a = document.createElement('a')
        a.href = URL.createObjectURL(blob)
        a.download = `evidence-${form.date_from}-${form.date_to}.csv`
        a.click()
      })
  }

  const when = (iso) => (iso ? new Date(iso).toLocaleString(dateLocale(lang)) : '–')

  return (
    <section className="card wide">
      <h2>{t('Evidence report')}</h2>
      <p className="muted small">
        {t('Every change in a period, with who requested it, who approved it and why – the document an audit asks for, instead of an API to query one record at a time.')}
      </p>

      <div className="filterbar no-print">
        <label>{t('From')}
          <input type="date" value={form.date_from} onChange={set('date_from')} />
        </label>
        <label>{t('To')}
          <input type="date" value={form.date_to} onChange={set('date_to')} />
        </label>
        <label>{t('Zone')}
          <input value={form.zone} onChange={set('zone')} placeholder={t('all zones')} />
        </label>
        <label>{t('Application')}
          <input value={form.app_id} onChange={set('app_id')} placeholder={t('all applications')} />
        </label>
        <button className="btn btn-primary" onClick={run} disabled={busy}>
          {t('Create report')}
        </button>
        {data && (
          <>
            <button className="btn" onClick={() => window.print()}>{t('Print / PDF')}</button>
            <button className="btn" onClick={csv}>CSV</button>
          </>
        )}
      </div>

      {error && <div className="error">{error}</div>}

      {data && (
        <div className="evidence">
          <p className="muted small">
            {t('Period')}: <strong>{data.scope.from} – {data.scope.to}</strong>
            {data.scope.zone && <> · {t('Zone')}: <strong>{data.scope.zone}</strong></>}
            {data.scope.app_id && <> · {t('Application')}: <strong>{data.scope.app_id}</strong></>}
            {' · '}{t('Created')}: {when(data.generated_at)}
          </p>

          {/* The integrity block is the point of the document being generated by
              the system that holds the records: it states what it can vouch for
              rather than leaving the reader to assume. */}
          <div className={`evidence-integrity ${data.integrity.chain_ok && data.integrity.audit_log_covers_period ? 'ok' : 'warn'}`}>
            <div>
              {data.integrity.chain_ok
                ? t('Audit chain verified – unbroken and unchanged.')
                : t('Audit chain NOT verified – the log has been altered or truncated.')}
              {data.integrity.chain_collapsed > 0 && (
                <> {t('{n} older entries were removed under the retention policy and are covered by a seal.')
                  .replace('{n}', data.integrity.chain_collapsed)}</>
              )}
            </div>
            {!data.integrity.audit_log_covers_period && (
              <div>
                <strong>{t('Note:')}</strong>{' '}
                {t('The period reaches back beyond the audit log retention. The change history below is complete – the corroborating log entries for the earliest part are not.')}
              </div>
            )}
            <div className="muted small">
              {t('Rule and matrix change records are not subject to retention and are complete for the period.')}
            </div>
          </div>

          <h3>{t('Rule changes')} ({data.totals.rule_changes})</h3>
          {data.rule_changes.length === 0
            ? <p className="muted">{t('No rule was changed in this period.')}</p>
            : data.rule_changes.map((rule) => (
              <div key={rule.rule_id} className="evidence-rule">
                <h4>
                  <code>{rule.rule_id}</code> {rule.name}
                  {rule.deleted && <> · <span className="badge status-deactivated">{t('deleted')}</span></>}
                </h4>
                <p className="muted small">
                  {rule.source_zone} → {rule.destination_zone}
                  {' · '}{t('Requestor')}: <strong>{rule.requestor || '–'}</strong>
                  {rule.change_id && <> · {t('Change')}: {rule.change_id}</>}
                </p>
                {rule.justification && (
                  <p className="small"><em>{t('Justification')}:</em> {rule.justification}</p>
                )}
                <div className="table-wrap">
                  <table>
                    <thead>
                      <tr><th>{t('Date')}</th><th>{t('Person')}</th><th>{t('Change')}</th></tr>
                    </thead>
                    <tbody>
                      {rule.changes.map((c) => (
                        <tr key={c.version}>
                          <td>{when(c.date)}</td><td>{c.actor}</td><td>{c.what}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            ))}

          <h3>{t('Zone and matrix changes')} ({data.totals.zone_changes})</h3>
          {data.zone_changes.length === 0
            ? <p className="muted">{t('No zone or matrix change in this period.')}</p>
            : (
              <div className="table-wrap">
                <table>
                  <thead>
                    <tr>
                      <th>{t('Date')}</th><th>{t('Change')}</th>
                      <th>{t('Requested by')}</th>
                      {/* Both approvers: two is what a matrix change requires,
                          and naming one would misrepresent the control. */}
                      <th>{t('1st approval')}</th><th>{t('2nd approval')}</th>
                      <th>{t('Status')}</th><th>{t('Justification')}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {data.zone_changes.map((c, i) => (
                      <tr key={i}>
                        <td>{when(c.date)}</td>
                        <td>
                          {c.from_zone}{c.to_zone && <> → {c.to_zone}</>}
                          <br /><span className="muted small">
                            {c.old_policy || '–'} → {c.new_policy}
                          </span>
                        </td>
                        <td>{c.requested_by || '–'}</td>
                        <td>{c.first_approved_by || '–'}</td>
                        <td>{c.approved_by || '–'}</td>
                        <td>{t(c.status)}</td>
                        <td>{c.justification}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
        </div>
      )}
    </section>
  )
}
