"""zone networks

Revision ID: 00bd30f1e4b4
Revises: fe9db5c0d5c4
Create Date: 2026-08-21 18:31:43.697474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00bd30f1e4b4'
down_revision: Union[str, Sequence[str], None] = 'fe9db5c0d5c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidr', sa.String(length=64), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zone_networks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zone_networks_cidr'), ['cidr'], unique=True)
        batch_op.create_index(batch_op.f('ix_zone_networks_zone_id'), ['zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_networks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zone_networks_zone_id'))
        batch_op.drop_index(batch_op.f('ix_zone_networks_cidr'))

    op.drop_table('zone_networks')
    # ### end Alembic commands ###
