"""epg catalog and address epg map

Revision ID: 0317086962e2
Revises: 61a6268b57a1
Create Date: 2026-08-21 00:20:51.814723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0317086962e2'
down_revision: Union[str, Sequence[str], None] = '61a6268b57a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tenant', sa.String(length=64), nullable=False),
    sa.Column('app_profile', sa.String(length=64), nullable=False),
    sa.Column('bridge_domain', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('epgs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_epgs_name'), ['name'], unique=True)

    op.create_table('address_epg_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.Column('epg_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['epg_id'], ['epgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('address_epg_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address_epg_map_epg_id'), ['epg_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_address_epg_map_ip'), ['ip'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address_epg_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_epg_map_ip'))
        batch_op.drop_index(batch_op.f('ix_address_epg_map_epg_id'))

    op.drop_table('address_epg_map')
    with op.batch_alter_table('epgs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_epgs_name'))

    op.drop_table('epgs')
    # ### end Alembic commands ###
