"""baseline schema

Revision ID: 3ce566c3f159
Revises: 
Create Date: 2026-08-20 23:58:54.441832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce566c3f159'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_component_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.Column('component_ids', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('address_component_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address_component_map_ip'), ['ip'], unique=True)

    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('application', sa.String(length=128), nullable=False),
    sa.Column('source_zone', sa.Text(), nullable=False),
    sa.Column('destination_zone', sa.Text(), nullable=False),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.Column('destination', sa.JSON(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('action', sa.Enum('permit', 'deny', name='ruleaction'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('business_context', sa.String(length=256), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('requestor', sa.String(length=128), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('change_id', sa.String(length=128), nullable=False),
    sa.Column('valid_from', sa.String(length=10), nullable=True),
    sa.Column('valid_until', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_review', 'approved', 'rejected', 'deactivated', name='rulestatus'), nullable=False),
    sa.Column('impl_status', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_application'), ['application'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_rule_id'), ['rule_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_rules_status'), ['status'], unique=False)

    op.create_table('security_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('juniper', 'checkpoint', 'aci', name='componenttype'), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('mgmt_address', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_components_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('architect', 'operations', 'admin', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zones_name'), ['name'], unique=True)

    op.create_table('aci_gateways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tenant', sa.String(length=64), nullable=False),
    sa.Column('vrf', sa.String(length=64), nullable=False),
    sa.Column('bridge_domain', sa.String(length=64), nullable=False),
    sa.Column('gateway_ip', sa.String(length=64), nullable=False),
    sa.Column('zone_name', sa.String(length=64), nullable=False),
    sa.Column('pbr_enabled', sa.Boolean(), nullable=False),
    sa.Column('pbr_component_id', sa.Integer(), nullable=True),
    sa.Column('pbr_node_ip', sa.String(length=64), nullable=False),
    sa.Column('pbr_node_mac', sa.String(length=32), nullable=False),
    sa.Column('pbr_service_graph', sa.String(length=128), nullable=False),
    sa.Column('pbr_health_group', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pbr_component_id'], ['security_components.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aci_gateways', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aci_gateways_name'), ['name'], unique=True)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_pk', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_pk'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_rule_pk'), ['rule_pk'], unique=False)

    op.create_table('rule_components',
    sa.Column('rule_pk', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['security_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_pk'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_pk', 'component_id')
    )
    op.create_table('rule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_pk', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.String(length=64), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_pk'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_pk', 'version')
    )
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_versions_rule_pk'), ['rule_pk'], unique=False)

    op.create_table('zone_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_zone_id', sa.Integer(), nullable=False),
    sa.Column('to_zone_id', sa.Integer(), nullable=False),
    sa.Column('policy', sa.Enum('allow_only', 'block_all', name='zonepolicytype'), nullable=False),
    sa.Column('temporary', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['from_zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_zone_id', 'to_zone_id')
    )
    with op.batch_alter_table('zone_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zone_policies_from_zone_id'), ['from_zone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_zone_policies_to_zone_id'), ['to_zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zone_policies_to_zone_id'))
        batch_op.drop_index(batch_op.f('ix_zone_policies_from_zone_id'))

    op.drop_table('zone_policies')
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_versions_rule_pk'))

    op.drop_table('rule_versions')
    op.drop_table('rule_components')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_rule_pk'))

    op.drop_table('comments')
    with op.batch_alter_table('aci_gateways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aci_gateways_name'))

    op.drop_table('aci_gateways')
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zones_name'))

    op.drop_table('zones')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('security_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_components_name'))

    op.drop_table('security_components')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_status'))
        batch_op.drop_index(batch_op.f('ix_rules_rule_id'))
        batch_op.drop_index(batch_op.f('ix_rules_application'))

    op.drop_table('rules')
    with op.batch_alter_table('address_component_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_component_map_ip'))

    op.drop_table('address_component_map')
    # ### end Alembic commands ###
