"""drift configs and object catalog

Revision ID: 61a6268b57a1
Revises: 3ce566c3f159
Create Date: 2026-08-21 00:05:02.075140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a6268b57a1'
down_revision: Union[str, Sequence[str], None] = '3ce566c3f159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('address_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address_objects_name'), ['name'], unique=True)

    op.create_table('service_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('port', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_objects_name'), ['name'], unique=True)

    op.create_table('component_actual_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['security_components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('component_actual_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_component_actual_configs_component_id'), ['component_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_actual_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component_actual_configs_component_id'))

    op.drop_table('component_actual_configs')
    with op.batch_alter_table('service_objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_objects_name'))

    op.drop_table('service_objects')
    with op.batch_alter_table('address_objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_objects_name'))

    op.drop_table('address_objects')
    # ### end Alembic commands ###
