"""zone pap level

Revision ID: 685a9459b4e9
Revises: 9e0c3c79c4d5
Create Date: 2026-08-21 08:03:33.295194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685a9459b4e9'
down_revision: Union[str, Sequence[str], None] = '9e0c3c79c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pap_level', sa.String(length=16), server_default='intern', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_column('pap_level')

    # ### end Alembic commands ###
