"""network source

Revision ID: 77ff0bcd4a64
Revises: 00bd30f1e4b4
Create Date: 2026-08-21 18:43:04.523982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ff0bcd4a64'
down_revision: Union[str, Sequence[str], None] = '00bd30f1e4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_networks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=32), server_default='manual', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_networks', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
