"""component link type

Revision ID: 9e0c3c79c4d5
Revises: cb684f2dd394
Create Date: 2026-08-21 07:23:37.331962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0c3c79c4d5'
down_revision: Union[str, Sequence[str], None] = 'cb684f2dd394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_type', sa.String(length=64), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_links', schema=None) as batch_op:
        batch_op.drop_column('link_type')

    # ### end Alembic commands ###
