"""change batches

Revision ID: c792aca55f66
Revises: d8e4af3c69e0
Create Date: 2026-08-21 08:23:15.706589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c792aca55f66'
down_revision: Union[str, Sequence[str], None] = 'd8e4af3c69e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_policy_changes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.String(length=36), server_default='', nullable=False))
        batch_op.add_column(sa.Column('change_type', sa.String(length=16), server_default='policy', nullable=False))
        batch_op.create_index(batch_op.f('ix_zone_policy_changes_batch_id'), ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_policy_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zone_policy_changes_batch_id'))
        batch_op.drop_column('change_type')
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
