"""component ns tier

Revision ID: cb684f2dd394
Revises: f2d472373e77
Create Date: 2026-08-21 07:13:16.477001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb684f2dd394'
down_revision: Union[str, Sequence[str], None] = 'f2d472373e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ns_tier', sa.Integer(), server_default='100', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_components', schema=None) as batch_op:
        batch_op.drop_column('ns_tier')

    # ### end Alembic commands ###
