"""zone policy changes

Revision ID: d8e4af3c69e0
Revises: 685a9459b4e9
Create Date: 2026-08-21 08:13:49.079389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e4af3c69e0'
down_revision: Union[str, Sequence[str], None] = '685a9459b4e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_policy_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_zone', sa.String(length=64), nullable=False),
    sa.Column('to_zone', sa.String(length=64), nullable=False),
    sa.Column('old_policy', sa.String(length=16), nullable=True),
    sa.Column('new_policy', sa.String(length=16), nullable=False),
    sa.Column('old_temporary', sa.Boolean(), nullable=False),
    sa.Column('new_temporary', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zone_policy_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zone_policy_changes_from_zone'), ['from_zone'], unique=False)
        batch_op.create_index(batch_op.f('ix_zone_policy_changes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_zone_policy_changes_to_zone'), ['to_zone'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_policy_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zone_policy_changes_to_zone'))
        batch_op.drop_index(batch_op.f('ix_zone_policy_changes_status'))
        batch_op.drop_index(batch_op.f('ix_zone_policy_changes_from_zone'))

    op.drop_table('zone_policy_changes')
    # ### end Alembic commands ###
