"""component links

Revision ID: f2d472373e77
Revises: 0317086962e2
Create Date: 2026-08-21 07:09:03.349547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d472373e77'
down_revision: Union[str, Sequence[str], None] = '0317086962e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_a_id', sa.Integer(), nullable=False),
    sa.Column('component_b_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['component_a_id'], ['security_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_b_id'], ['security_components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_a_id', 'component_b_id')
    )
    with op.batch_alter_table('component_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_component_links_component_a_id'), ['component_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_component_links_component_b_id'), ['component_b_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component_links_component_b_id'))
        batch_op.drop_index(batch_op.f('ix_component_links_component_a_id'))

    op.drop_table('component_links')
    # ### end Alembic commands ###
