"""zone components

Revision ID: fe9db5c0d5c4
Revises: 4d6e0f7ee14f
Create Date: 2026-08-21 18:27:48.077559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9db5c0d5c4'
down_revision: Union[str, Sequence[str], None] = '4d6e0f7ee14f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_components',
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['security_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('zone_id', 'component_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('architect', 'operations', 'change_approver', 'admin', name='role'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('architect', 'operations', 'change_approver', 'admin', name='role'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    op.drop_table('zone_components')
    # ### end Alembic commands ###
