## Netzwart Export – Juniper SRX (set-Kommandos)
## Regeln: SR0101
# SR0101: Demo: absichtlich überlappende Regel für Konflikt-Warnung
# Change: CHN2026999
set security zones security-zone VPN address-book address NET-VPN 10.10.20.0/24
set security zones security-zone MGMT address-book address jump01.demo.local 10.10.80.10/32
set applications application tcp-22 protocol tcp
set applications application tcp-22 destination-port 22
set security policies from-zone VPN to-zone MGMT policy Konflikt-Demo-SR0101 match source-address NET-VPN
set security policies from-zone VPN to-zone MGMT policy Konflikt-Demo-SR0101 match destination-address jump01.demo.local
set security policies from-zone VPN to-zone MGMT policy Konflikt-Demo-SR0101 match application tcp-22
set security policies from-zone VPN to-zone MGMT policy Konflikt-Demo-SR0101 then permit
set security policies from-zone VPN to-zone MGMT policy Konflikt-Demo-SR0101 then log session-init session-close
